# Generated by Django 3.2.8 on 2021-10-17 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(default='NULL', max_length=100, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('born_date', models.DateField(null=True)),
                ('is_host', models.BooleanField(default=False)),
                ('is_houseHolder', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(choices=[('AP', 'Apartamento'), ('FC', 'Finca'), ('CS', 'Casa'), ('AS', 'Aparta-estudios')], max_length=100)),
                ('descripcion', models.CharField(default='No hay descripción', max_length=500)),
                ('precio', models.IntegerField()),
                ('num_habitaciones', models.IntegerField()),
                ('num_baños', models.IntegerField()),
                ('area', models.CharField(max_length=20)),
                ('aparcamiento', models.BooleanField(default=False)),
                ('amoblado', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('seguridad', models.BooleanField(default=False)),
                ('imagenesPrincipal', models.ImageField(null=True, upload_to='inmuebles/')),
                ('imagenes1', models.ImageField(null=True, upload_to='inmuebles/')),
                ('imagenes2', models.ImageField(null=True, upload_to='inmuebles/')),
                ('imagenes3', models.ImageField(null=True, upload_to='inmuebles/')),
                ('fechacreacion', models.DateField(default=django.utils.timezone.now)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='inmuebles.inmueble')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
