# Generated by Django 3.2.8 on 2021-10-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagenes1',
            new_name='imagen1',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagenes2',
            new_name='imagen2',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagenes3',
            new_name='imagen3',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagenesPrincipal',
            new_name='imagenPrincipal',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='NULL', max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
