# Generated by Django 3.2.8 on 2021-10-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_alter_user_born_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
