# Generated by Django 3.2.8 on 2021-10-17 23:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20211017_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='id_url',
            field=autoslug.fields.AutoSlugField(default='sin-ur-id', editable=False, populate_from='titulo', unique=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='titulo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
