# Generated by Django 3.2.8 on 2021-10-17 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_inmueble_id_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fechacreacion',
            field=models.DateField(default=datetime.datetime(2021, 10, 17, 23, 52, 8, 53357, tzinfo=utc)),
        ),
    ]
