# Generated by Django 3.2.8 on 2021-10-12 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_auto_20211011_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(choices=[('AP', 'Apartamento'), ('FC', 'Finca'), ('CS', 'Casa'), ('AS', 'Aparta-estudios')], max_length=100)),
                ('descripcion', models.CharField(default='No hay descripción', max_length=500)),
                ('precio', models.IntegerField()),
                ('num_habitaciones', models.IntegerField()),
                ('num_baños', models.IntegerField()),
                ('area', models.CharField(max_length=20)),
                ('aparcamiento', models.BooleanField(default=False)),
                ('amoblado', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('seguridad', models.BooleanField(default=False)),
                ('imagenes', models.ImageField(upload_to='')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='inmuebles.inmueble')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
