# Generated by Django 3.2.8 on 2021-10-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_auto_20211014_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_houseHolder',
        ),
    ]
