# Generated by Django 3.2.8 on 2021-10-20 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_alter_inmueble_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fechacreacion',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
