# Generated by Django 3.2.8 on 2021-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_auto_20211014_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_houseHolder',
            field=models.BooleanField(default=True),
        ),
    ]
