# Generated by Django 3.2.8 on 2021-11-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0008_alter_inmueble_fechacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroinmueble',
            name='id_inmueble',
        ),
        migrations.RemoveField(
            model_name='registroinmueble',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
        migrations.DeleteModel(
            name='RegistroInmueble',
        ),
    ]
